In [115]:
import pandas as pd, numpy as np, sklearn, matplotlib.pyplot as plt, seaborn as sns, statsmodels as sm

In [116]:
# !pip install yfinance

In [117]:
# !pip install PyPortfolioOpt

In [118]:
# !pip install Datetime

In [119]:
# !pip install pandas_datareader

In [120]:
# !pip install pandas_ta

In [121]:
from statsmodels.regression.rolling import RollingOLS
import pandas_datareader as web
import datetime as dt 
import yfinance as yf
import pandas_ta, warnings
warnings.filterwarnings('ignore')

reading the data from wikipedia to know about sp500 list

In [122]:
sp500=pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')[0]

storing the symbol and handling errors in symbol

In [123]:
symbol_list=sp500['Symbol'].replace('.','-').tolist()
symbol_list

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ACN',
 'ADBE',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'ABNB',
 'AKAM',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE',
 'AAL',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'AME',
 'AMGN',
 'APH',
 'ADI',
 'ANSS',
 'AON',
 'APA',
 'AAPL',
 'AMAT',
 'APTV',
 'ACGL',
 'ADM',
 'ANET',
 'AJG',
 'AIZ',
 'T',
 'ATO',
 'ADSK',
 'ADP',
 'AZO',
 'AVB',
 'AVY',
 'AXON',
 'BKR',
 'BALL',
 'BAC',
 'BK',
 'BBWI',
 'BAX',
 'BDX',
 'BRK.B',
 'BBY',
 'BIO',
 'TECH',
 'BIIB',
 'BLK',
 'BX',
 'BA',
 'BKNG',
 'BWA',
 'BXP',
 'BSX',
 'BMY',
 'AVGO',
 'BR',
 'BRO',
 'BF.B',
 'BLDR',
 'BG',
 'CDNS',
 'CZR',
 'CPT',
 'CPB',
 'COF',
 'CAH',
 'KMX',
 'CCL',
 'CARR',
 'CTLT',
 'CAT',
 'CBOE',
 'CBRE',
 'CDW',
 'CE',
 'COR',
 'CNC',
 'CNP',
 'CDAY',
 'CF',
 'CHRW',
 'CRL',
 'SCHW',
 'CHTR',
 'CVX',
 'CMG',
 'CB',
 'CHD',
 'CI',
 'CINF',
 'CTAS',
 'CSCO',
 'C',
 'CFG',
 'CLX',
 'CME',
 'CMS',
 'KO',
 'CTSH',
 'CL',
 'CMCSA',
 'CMA',
 'CAG',
 'COP',
 'ED',
 'STZ',
 'CEG',
 'COO',
 'CPRT',
 'GLW',
 'CTVA',
 'CSGP',
 'COST',
 'CTRA',
 'CCI',
 'CSX',
 'CMI',
 'CVS',
 'DHR',
 'DRI',
 'DVA',
 'DE',
 'DAL',
 'XRAY',
 'DVN',
 'DXCM',
 'FANG',
 'DLR',
 'DFS',
 'DG',
 'DLTR',
 'D',
 'DPZ',
 'DOV',
 'DOW',
 'DHI',
 'DTE',
 'DUK',
 'DD',
 'EMN',
 'ETN',
 'EBAY',
 'ECL',
 'EIX',
 'EW',
 'EA',
 'ELV',
 'LLY',
 'EMR',
 'ENPH',
 'ETR',
 'EOG',
 'EPAM',
 'EQT',
 'EFX',
 'EQIX',
 'EQR',
 'ESS',
 'EL',
 'ETSY',
 'EG',
 'EVRG',
 'ES',
 'EXC',
 'EXPE',
 'EXPD',
 'EXR',
 'XOM',
 'FFIV',
 'FDS',
 'FICO',
 'FAST',
 'FRT',
 'FDX',
 'FIS',
 'FITB',
 'FSLR',
 'FE',
 'FI',
 'FLT',
 'FMC',
 'F',
 'FTNT',
 'FTV',
 'FOXA',
 'FOX',
 'BEN',
 'FCX',
 'GRMN',
 'IT',
 'GEHC',
 'GEN',
 'GNRC',
 'GD',
 'GE',
 'GIS',
 'GM',
 'GPC',
 'GILD',
 'GPN',
 'GL',
 'GS',
 'HAL',
 'HIG',
 'HAS',
 'HCA',
 'PEAK',
 'HSIC',
 'HSY',
 'HES',
 'HPE',
 'HLT',
 'HOLX',
 'HD',
 'HON',
 'HRL',
 'HST',
 'HWM',
 'HPQ',
 'HUBB',
 'HUM',
 'HBAN',
 'HII',
 'IBM',
 'IEX',
 'IDXX',
 'ITW',
 'ILMN',
 'INCY',
 'IR',
 'PODD',
 'INTC',
 'ICE',
 'IFF',
 'IP',
 'IPG',
 'INTU',
 'ISRG',
 'IVZ',
 'INVH',
 'IQV',
 'IRM',
 'JBHT',
 'JBL',
 'JKHY',
 'J',
 'JNJ',
 'JCI',
 'JPM',
 'JNPR',
 'K',
 'KVUE',
 'KDP',
 'KEY',
 'KEYS',
 'KMB',
 'KIM',
 'KMI',
 'KLAC',
 'KHC',
 'KR',
 'LHX',
 'LH',
 'LRCX',
 'LW',
 'LVS',
 'LDOS',
 'LEN',
 'LIN',
 'LYV',
 'LKQ',
 'LMT',
 'L',
 'LOW',
 'LULU',
 'LYB',
 'MTB',
 'MRO',
 'MPC',
 'MKTX',
 'MAR',
 'MMC',
 'MLM',
 'MAS',
 'MA',
 'MTCH',
 'MKC',
 'MCD',
 'MCK',
 'MDT',
 'MRK',
 'META',
 'MET',
 'MTD',
 'MGM',
 'MCHP',
 'MU',
 'MSFT',
 'MAA',
 'MRNA',
 'MHK',
 'MOH',
 'TAP',
 'MDLZ',
 'MPWR',
 'MNST',
 'MCO',
 'MS',
 'MOS',
 'MSI',
 'MSCI',
 'NDAQ',
 'NTAP',
 'NFLX',
 'NEM',
 'NWSA',
 'NWS',
 'NEE',
 'NKE',
 'NI',
 'NDSN',
 'NSC',
 'NTRS',
 'NOC',
 'NCLH',
 'NRG',
 'NUE',
 'NVDA',
 'NVR',
 'NXPI',
 'ORLY',
 'OXY',
 'ODFL',
 'OMC',
 'ON',
 'OKE',
 'ORCL',
 'OTIS',
 'PCAR',
 'PKG',
 'PANW',
 'PARA',
 'PH',
 'PAYX',
 'PAYC',
 'PYPL',
 'PNR',
 'PEP',
 'PFE',
 'PCG',
 'PM',
 'PSX',
 'PNW',
 'PXD',
 'PNC',
 'POOL',
 'PPG',
 'PPL',
 'PFG',
 'PG',
 'PGR',
 'PLD',
 'PRU',
 'PEG',
 'PTC',
 'PSA',
 'PHM',
 'QRVO',
 'PWR',
 'QCOM',
 'DGX',
 'RL',
 'RJF',
 'RTX',
 'O',
 'REG',
 'REGN',
 'RF',
 'RSG',
 'RMD',
 'RVTY',
 'RHI',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RCL',
 'SPGI',
 'CRM',
 'SBAC',
 'SLB',
 'STX',
 'SRE',
 'NOW',
 'SHW',
 'SPG',
 'SWKS',
 'SJM',
 'SNA',
 'SO',
 'LUV',
 'SWK',
 'SBUX',
 'STT',
 'STLD',
 'STE',
 'SYK',
 'SYF',
 'SNPS',
 'SYY',
 'TMUS',
 'TROW',
 'TTWO',
 'TPR',
 'TRGP',
 'TGT',
 'TEL',
 'TDY',
 'TFX',
 'TER',
 'TSLA',
 'TXN',
 'TXT',
 'TMO',
 'TJX',
 'TSCO',
 'TT',
 'TDG',
 'TRV',
 'TRMB',
 'TFC',
 'TYL',
 'TSN',
 'USB',
 'UBER',
 'UDR',
 'ULTA',
 'UNP',
 'UAL',
 'UPS',
 'URI',
 'UNH',
 'UHS',
 'VLO',
 'VTR',
 'VLTO',
 'VRSN',
 'VRSK',
 'VZ',
 'VRTX',
 'VFC',
 'VTRS',
 'VICI',
 'V',
 'VMC',
 'WRB',
 'WAB',
 'WBA',
 'WMT',
 'DIS',
 'WBD',
 'WM',
 'WAT',
 'WEC',
 'WFC',
 'WELL',
 'WST',
 'WDC',
 'WRK',
 'WY',
 'WHR',
 'WMB',
 'WTW',
 'GWW',
 'WYNN',
 'XEL',
 'XYL',
 'YUM',
 'ZBRA',
 'ZBH',
 'ZION',
 'ZTS']

downloading data to get started

In [124]:
 original=yf.download(tickers=symbol_list, start=start_date, end=end_date ).stack()

[*********************100%%**********************]  503 of 503 completed

3 Failed downloads:
['BF.B']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2010-01-01 -> 2023-09-27)')
['BRK.B']: Exception('%ticker%: No timezone found, symbol may be delisted')
['VLTO']: Exception("%ticker%: Data doesn't exist for startDate = 1262322000, endDate = 1695787200")

In [125]:
df=original.copy()

In [126]:
df

Price               Adj Close       Close        High         Low        Open  \
Date       Ticker
2010-01-04 A        20.154911   22.389128   22.625179   22.267525   22.453505
           AAL       4.496877    4.770000    4.940000    4.660000    4.840000
           AAPL      6.478999    7.643214    7.660714    7.585000    7.622500
           ABT      19.046160   26.129908   26.177889   25.870815   26.000362
           ACGL      7.994444    7.994444    8.022222    7.972222    7.978889
...                       ...         ...         ...         ...         ...
2023-09-26 YUM     123.426186  124.010002  124.739998  123.449997  124.239998
           ZBH     111.992920  112.459999  117.110001  112.419998  116.769997
           ZBRA    223.960007  223.960007  226.649994  222.580002  225.970001
           ZION     33.581326   33.990002   34.700001   33.840000   33.840000
           ZTS     176.048248  176.869995  178.449997  176.270004  176.580002

Price                   Volume
Date       Ticker
2010-01-04 A         3815561.0
           AAL       9837300.0
           AAPL    493729600.0
           ABT      10829095.0
           ACGL      4813200.0
...                        ...
2023-09-26 YUM       1500600.0
           ZBH       3610500.0
           ZBRA       355400.0
           ZION      1586100.0
           ZTS       1463200.0

[1651548 rows x 6 columns]

In [127]:
df.index.names=['Date','Tickers']

In [128]:
df.index

MultiIndex([('2010-01-04',    'A'),
            ('2010-01-04',  'AAL'),
            ('2010-01-04', 'AAPL'),
            ('2010-01-04',  'ABT'),
            ('2010-01-04', 'ACGL'),
            ('2010-01-04',  'ACN'),
            ('2010-01-04', 'ADBE'),
            ('2010-01-04',  'ADI'),
            ('2010-01-04',  'ADM'),
            ('2010-01-04',  'ADP'),
            ...
            ('2023-09-26', 'WYNN'),
            ('2023-09-26',  'XEL'),
            ('2023-09-26',  'XOM'),
            ('2023-09-26', 'XRAY'),
            ('2023-09-26',  'XYL'),
            ('2023-09-26',  'YUM'),
            ('2023-09-26',  'ZBH'),
            ('2023-09-26', 'ZBRA'),
            ('2023-09-26', 'ZION'),
            ('2023-09-26',  'ZTS')],
           names=['Date', 'Tickers'], length=1651548)

• Garman-Klass Volatility

• RSI

• Bollinger Bands

• ATR

• MACD

• Dollar Volume

In [129]:
df['Garman'] = ((((np.log(df['High']) - np.log(df['Low']))**2) / 2) -
                ((2 * np.log(2) - 1) * (np.log(df['Adj Close']) - np.log(df['Open']))**2))

In [130]:
pandas_ta.rsi?
df['rsi']=df.groupby(by='Tickers')['Adj Close'].transform(lambda x :pandas_ta.rsi(close=x, length=20, ) )

Signature:
pandas_ta.rsi(
    close,
    length=None,
    scalar=None,
    talib=None,
    drift=None,
    offset=None,
    **kwargs,
)
Docstring:
Relative Strength Index (RSI)

The Relative Strength Index is popular momentum oscillator used to measure the
velocity as well as the magnitude of directional price movements.

Sources:
    https://www.tradingview.com/wiki/Relative_Strength_Index_(RSI)

Calculation:
    Default Inputs:
        length=14, scalar=100, drift=1
    ABS = Absolute Value
    RMA = Rolling Moving Average

    diff = close.diff(drift)
    positive = diff if diff > 0 else 0
    negative = diff if diff < 0 else 0

    pos_avg = RMA(positive, length)
    neg_avg = ABS(RMA(negative, length))

    RSI = scalar * pos_avg / (pos_avg + neg_avg)

Args:
    close (pd.Series): Series of 'close's
    length (int): It's period. Default: 14
    scalar (float): How much to magnify. Default: 100
    talib (bool): If TA Lib is installed and talib is True, Returns the TA Lib
        version. Default: True
    drift (int): The difference period. Default: 1
    offset (int): How many periods to offset the result. Default: 0

Kwargs:
    fillna (value, optional): pd.DataFrame.fillna(value)
    fill_method (value, optional): Type of fill method

Returns:
    pd.Series: New feature generated.
File:      c:\users\dhima\anaconda3\lib\site-packages\pandas_ta\momentum\rsi.py
Type:      function

In [131]:
# pandas_ta.bbands?
df['band_low']=df.groupby('Tickers')['Adj Close'].transform(lambda x:pandas_ta.bbands(close=np.log1p(x), length=20).iloc[:,0])
df['band_med']=df.groupby('Tickers')['Adj Close'].transform(lambda x:pandas_ta.bbands(close=np.log1p(x), length=20).iloc[:,1])
df['band_high']=df.groupby('Tickers')['Adj Close'].transform(lambda x:pandas_ta.bbands(close=np.log1p(x), length=20).iloc[:,2])

In [132]:
# pandas_ta.atr?
def atr(inp):
    atr_series = pandas_ta.atr(high=inp['High'], low=inp['Low'], close=inp['Close'], length=14)
    return atr_series.sub(atr_series.mean()).div(atr_series.std())

In [133]:
df['atr']=df.groupby(by='Tickers', group_keys=False).apply(atr)

In [134]:
# pandas_ta.macd?
def macd(close):
    macd=pandas_ta.macd(close=close,length=20 ).iloc[:,0]
    return macd.sub(macd.mean()).div(macd.std())

In [135]:
df.groupby(by='Tickers', group_keys=False)['Adj Close'].apply(macd)

Date        Tickers
2010-01-04  A               NaN
            AAL             NaN
            AAPL            NaN
            ABT             NaN
            ACGL            NaN
                         ...
2023-09-26  YUM       -1.627382
            ZBH       -1.108750
            ZBRA      -2.045456
            ZION      -0.208176
            ZTS       -1.302306
Name: Adj Close, Length: 1651548, dtype: float64

In [136]:
df['dollar_volume']= df['Adj Close']*df['Volume']/1000000

In [137]:
df.head()

Price               Adj Close      Close       High        Low       Open  \
Date       Tickers
2010-01-04 A        20.154911  22.389128  22.625179  22.267525  22.453505
           AAL       4.496877   4.770000   4.940000   4.660000   4.840000
           AAPL      6.478999   7.643214   7.660714   7.585000   7.622500
           ABT      19.046160  26.129908  26.177889  25.870815  26.000362
           ACGL      7.994444   7.994444   8.022222   7.972222   7.978889

Price                    Volume    Garman  rsi  band_low  band_med  band_high  \
Date       Tickers
2010-01-04 A          3815561.0 -0.004379  NaN       NaN       NaN        NaN
           AAL        9837300.0 -0.000386  NaN       NaN       NaN        NaN
           AAPL     493729600.0 -0.010156  NaN       NaN       NaN        NaN
           ABT       10829095.0 -0.037352  NaN       NaN       NaN        NaN
           ACGL       4813200.0  0.000018  NaN       NaN       NaN        NaN

Price               atr  dollar_volume
Date       Tickers
2010-01-04 A        NaN      76.902293
           AAL      NaN      44.237130
           AAPL     NaN    3198.873653
           ABT      NaN     206.252673
           ACGL     NaN      38.478857

3. Aggregate monthly level and filter top 150

In [138]:
df.unstack('Tickers')['dollar_volume'].resample('M').mean().stack('Tickers')

Date        Tickers
2010-01-31  A            81.759620
            AAL          68.430825
            AAPL       4983.230771
            ABT         263.174850
            ACGL         28.610055
                          ...
2023-09-30  OTIS        155.565476
            ABNB       1633.500725
            CEG         197.358104
            GEHC        212.350630
            KVUE        684.902631
Length: 78880, dtype: float64

In [139]:
.to_frame?

Object `to_frame` not found.

In [140]:
df.resample?

Signature:
df.resample(
    rule,
    axis: 'Axis' = 0,
    closed: 'str | None' = None,
    label: 'str | None' = None,
    convention: 'str' = 'start',
    kind: 'str | None' = None,
    on: 'Level' = None,
    level: 'Level' = None,
    origin: 'str | TimestampConvertibleTypes' = 'start_day',
    offset: 'TimedeltaConvertibleTypes | None' = None,
    group_keys: 'bool' = False,
) -> 'Resampler'
Docstring:
Resample time-series data.

Convenience method for frequency conversion and resampling of time series.
The object must have a datetime-like index (`DatetimeIndex`, `PeriodIndex`,
or `TimedeltaIndex`), or the caller must pass the label of a datetime-like
series/index to the ``on``/``level`` keyword parameter.

Parameters
----------
rule : DateOffset, Timedelta or str
    The offset string or object representing target conversion.
axis : {0 or 'index', 1 or 'columns'}, default 0
    Which axis to use for up- or down-sampling. For `Series` this parameter
    is unused and defaults to 0. Must be
    `DatetimeIndex`, `TimedeltaIndex` or `PeriodIndex`.
closed : {'right', 'left'}, default None
    Which side of bin interval is closed. The default is 'left'
    for all frequency offsets except for 'M', 'A', 'Q', 'BM',
    'BA', 'BQ', and 'W' which all have a default of 'right'.
label : {'right', 'left'}, default None
    Which bin edge label to label bucket with. The default is 'left'
    for all frequency offsets except for 'M', 'A', 'Q', 'BM',
    'BA', 'BQ', and 'W' which all have a default of 'right'.
convention : {'start', 'end', 's', 'e'}, default 'start'
    For `PeriodIndex` only, controls whether to use the start or
    end of `rule`.
kind : {'timestamp', 'period'}, optional, default None
    Pass 'timestamp' to convert the resulting index to a
    `DateTimeIndex` or 'period' to convert it to a `PeriodIndex`.
    By default the input representation is retained.

on : str, optional
    For a DataFrame, column to use instead of index for resampling.
    Column must be datetime-like.
level : str or int, optional
    For a MultiIndex, level (name or number) to use for
    resampling. `level` must be datetime-like.
origin : Timestamp or str, default 'start_day'
    The timestamp on which to adjust the grouping. The timezone of origin
    must match the timezone of the index.
    If string, must be one of the following:

    - 'epoch': `origin` is 1970-01-01
    - 'start': `origin` is the first value of the timeseries
    - 'start_day': `origin` is the first day at midnight of the timeseries

    .. versionadded:: 1.1.0

    - 'end': `origin` is the last value of the timeseries
    - 'end_day': `origin` is the ceiling midnight of the last day

    .. versionadded:: 1.3.0

offset : Timedelta or str, default is None
    An offset timedelta added to the origin.

    .. versionadded:: 1.1.0

group_keys : bool, default False
    Whether to include the group keys in the result index when using
    ``.apply()`` on the resampled object.

    .. versionadded:: 1.5.0

        Not specifying ``group_keys`` will retain values-dependent behavior
        from pandas 1.4 and earlier (see :ref:`pandas 1.5.0 Release notes
        <whatsnew_150.enhancements.resample_group_keys>` for examples).

    .. versionchanged:: 2.0.0

        ``group_keys`` now defaults to ``False``.

Returns
-------
pandas.core.Resampler
    :class:`~pandas.core.Resampler` object.

See Also
--------
Series.resample : Resample a Series.
DataFrame.resample : Resample a DataFrame.
groupby : Group DataFrame by mapping, function, label, or list of labels.
asfreq : Reindex a DataFrame with the given frequency without grouping.

Notes
-----
See the `user guide
<https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#resampling>`__
for more.

To learn more about the offset strings, please see `this link
<https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#dateoffset-objects>`__.

Examples
--------
Start by creating a series with 9 one minute timestamps.

>>> index = pd.date_range('1/1/2000', periods=9, freq='T')
>>> series = pd.Series(range(9), index=index)
>>> series
2000-01-01 00:00:00    0
2000-01-01 00:01:00    1
2000-01-01 00:02:00    2
2000-01-01 00:03:00    3
2000-01-01 00:04:00    4
2000-01-01 00:05:00    5
2000-01-01 00:06:00    6
2000-01-01 00:07:00    7
2000-01-01 00:08:00    8
Freq: T, dtype: int64

Downsample the series into 3 minute bins and sum the values
of the timestamps falling into a bin.

>>> series.resample('3T').sum()
2000-01-01 00:00:00     3
2000-01-01 00:03:00    12
2000-01-01 00:06:00    21
Freq: 3T, dtype: int64

Downsample the series into 3 minute bins as above, but label each
bin using the right edge instead of the left. Please note that the
value in the bucket used as the label is not included in the bucket,
which it labels. For example, in the original series the
bucket ``2000-01-01 00:03:00`` contains the value 3, but the summed
value in the resampled bucket with the label ``2000-01-01 00:03:00``
does not include 3 (if it did, the summed value would be 6, not 3).
To include this value close the right side of the bin interval as
illustrated in the example below this one.

>>> series.resample('3T', label='right').sum()
2000-01-01 00:03:00     3
2000-01-01 00:06:00    12
2000-01-01 00:09:00    21
Freq: 3T, dtype: int64

Downsample the series into 3 minute bins as above, but close the right
side of the bin interval.

>>> series.resample('3T', label='right', closed='right').sum()
2000-01-01 00:00:00     0
2000-01-01 00:03:00     6
2000-01-01 00:06:00    15
2000-01-01 00:09:00    15
Freq: 3T, dtype: int64

Upsample the series into 30 second bins.

>>> series.resample('30S').asfreq()[0:5]   # Select first 5 rows
2000-01-01 00:00:00   0.0
2000-01-01 00:00:30   NaN
2000-01-01 00:01:00   1.0
2000-01-01 00:01:30   NaN
2000-01-01 00:02:00   2.0
Freq: 30S, dtype: float64

Upsample the series into 30 second bins and fill the ``NaN``
values using the ``ffill`` method.

>>> series.resample('30S').ffill()[0:5]
2000-01-01 00:00:00    0
2000-01-01 00:00:30    0
2000-01-01 00:01:00    1
2000-01-01 00:01:30    1
2000-01-01 00:02:00    2
Freq: 30S, dtype: int64

Upsample the series into 30 second bins and fill the
``NaN`` values using the ``bfill`` method.

>>> series.resample('30S').bfill()[0:5]
2000-01-01 00:00:00    0
2000-01-01 00:00:30    1
2000-01-01 00:01:00    1
2000-01-01 00:01:30    2
2000-01-01 00:02:00    2
Freq: 30S, dtype: int64

Pass a custom function via ``apply``

>>> def custom_resampler(arraylike):
...     return np.sum(arraylike) + 5
...
>>> series.resample('3T').apply(custom_resampler)
2000-01-01 00:00:00     8
2000-01-01 00:03:00    17
2000-01-01 00:06:00    26
Freq: 3T, dtype: int64

For a Series with a PeriodIndex, the keyword `convention` can be
used to control whether to use the start or end of `rule`.

Resample a year by quarter using 'start' `convention`. Values are
assigned to the first quarter of the period.

>>> s = pd.Series([1, 2], index=pd.period_range('2012-01-01',
...                                             freq='A',
...                                             periods=2))
>>> s
2012    1
2013    2
Freq: A-DEC, dtype: int64
>>> s.resample('Q', convention='start').asfreq()
2012Q1    1.0
2012Q2    NaN
2012Q3    NaN
2012Q4    NaN
2013Q1    2.0
2013Q2    NaN
2013Q3    NaN
2013Q4    NaN
Freq: Q-DEC, dtype: float64

Resample quarters by month using 'end' `convention`. Values are
assigned to the last month of the period.

>>> q = pd.Series([1, 2, 3, 4], index=pd.period_range('2018-01-01',
...                                                   freq='Q',
...                                                   periods=4))
>>> q
2018Q1    1
2018Q2    2
2018Q3    3
2018Q4    4
Freq: Q-DEC, dtype: int64
>>> q.resample('M', convention='end').asfreq()
2018-03    1.0
2018-04    NaN
2018-05    NaN
2018-06    2.0
2018-07    NaN
2018-08    NaN
2018-09    3.0
2018-10    NaN
2018-11    NaN
2018-12    4.0
Freq: M, dtype: float64

For DataFrame objects, the keyword `on` can be used to specify the
column instead of the index for resampling.

>>> d = {'price': [10, 11, 9, 13, 14, 18, 17, 19],
...      'volume': [50, 60, 40, 100, 50, 100, 40, 50]}
>>> df = pd.DataFrame(d)
>>> df['week_starting'] = pd.date_range('01/01/2018',
...                                     periods=8,
...                                     freq='W')
>>> df
   price  volume week_starting
0     10      50    2018-01-07
1     11      60    2018-01-14
2      9      40    2018-01-21
3     13     100    2018-01-28
4     14      50    2018-02-04
5     18     100    2018-02-11
6     17      40    2018-02-18
7     19      50    2018-02-25
>>> df.resample('M', on='week_starting').mean()
               price  volume
week_starting
2018-01-31     10.75    62.5
2018-02-28     17.00    60.0

For a DataFrame with MultiIndex, the keyword `level` can be used to
specify on which level the resampling needs to take place.

>>> days = pd.date_range('1/1/2000', periods=4, freq='D')
>>> d2 = {'price': [10, 11, 9, 13, 14, 18, 17, 19],
...       'volume': [50, 60, 40, 100, 50, 100, 40, 50]}
>>> df2 = pd.DataFrame(
...     d2,
...     index=pd.MultiIndex.from_product(
...         [days, ['morning', 'afternoon']]
...     )
... )
>>> df2
                      price  volume
2000-01-01 morning       10      50
           afternoon     11      60
2000-01-02 morning        9      40
           afternoon     13     100
2000-01-03 morning       14      50
           afternoon     18     100
2000-01-04 morning       17      40
           afternoon     19      50
>>> df2.resample('D', level=0).sum()
            price  volume
2000-01-01     21     110
2000-01-02     22     140
2000-01-03     32     150
2000-01-04     36      90

If you want to adjust the start of the bins based on a fixed timestamp:

>>> start, end = '2000-10-01 23:30:00', '2000-10-02 00:30:00'
>>> rng = pd.date_range(start, end, freq='7min')
>>> ts = pd.Series(np.arange(len(rng)) * 3, index=rng)
>>> ts
2000-10-01 23:30:00     0
2000-10-01 23:37:00     3
2000-10-01 23:44:00     6
2000-10-01 23:51:00     9
2000-10-01 23:58:00    12
2000-10-02 00:05:00    15
2000-10-02 00:12:00    18
2000-10-02 00:19:00    21
2000-10-02 00:26:00    24
Freq: 7T, dtype: int64

>>> ts.resample('17min').sum()
2000-10-01 23:14:00     0
2000-10-01 23:31:00     9
2000-10-01 23:48:00    21
2000-10-02 00:05:00    54
2000-10-02 00:22:00    24
Freq: 17T, dtype: int64

>>> ts.resample('17min', origin='epoch').sum()
2000-10-01 23:18:00     0
2000-10-01 23:35:00    18
2000-10-01 23:52:00    27
2000-10-02 00:09:00    39
2000-10-02 00:26:00    24
Freq: 17T, dtype: int64

>>> ts.resample('17min', origin='2000-01-01').sum()
2000-10-01 23:24:00     3
2000-10-01 23:41:00    15
2000-10-01 23:58:00    45
2000-10-02 00:15:00    45
Freq: 17T, dtype: int64

If you want to adjust the start of the bins with an `offset` Timedelta, the two
following lines are equivalent:

>>> ts.resample('17min', origin='start').sum()
2000-10-01 23:30:00     9
2000-10-01 23:47:00    21
2000-10-02 00:04:00    54
2000-10-02 00:21:00    24
Freq: 17T, dtype: int64

>>> ts.resample('17min', offset='23h30min').sum()
2000-10-01 23:30:00     9
2000-10-01 23:47:00    21
2000-10-02 00:04:00    54
2000-10-02 00:21:00    24
Freq: 17T, dtype: int64

If you want to take the largest Timestamp as the end of the bins:

>>> ts.resample('17min', origin='end').sum()
2000-10-01 23:35:00     0
2000-10-01 23:52:00    18
2000-10-02 00:09:00    27
2000-10-02 00:26:00    63
Freq: 17T, dtype: int64

In contrast with the `start_day`, you can use `end_day` to take the ceiling
midnight of the largest Timestamp as the end of the bins and drop the bins
not containing data:

>>> ts.resample('17min', origin='end_day').sum()
2000-10-01 23:38:00     3
2000-10-01 23:55:00    15
2000-10-02 00:12:00    45
2000-10-02 00:29:00    45
Freq: 17T, dtype: int64
File:      c:\users\dhima\anaconda3\lib\site-packages\pandas\core\frame.py
Type:      method

In [141]:
last_col= [c for c in df.columns.unique() if c not in ['dollar_volume', 'Volume', 'Open', 'High', 'Low','Close']]
df.unstack('Tickers')[last_col].resample('M').last().stack('Tickers')

Price                Adj Close    Garman       atr  band_high  band_low  \
Date       Tickers
2010-01-31 A         18.049276 -0.006263 -0.887814        NaN       NaN
           AAL        5.005958  0.002595 -1.230034        NaN       NaN
           AAPL       5.814477 -0.015367 -0.754456        NaN       NaN
           ABT       18.649780 -0.041882 -0.846116        NaN       NaN
           ACGL       7.948889  0.000093 -0.967571        NaN       NaN
...                        ...       ...       ...        ...       ...
2023-09-30 YUM      123.426186  0.000037  0.613277   4.881456  4.821521
           ZBH      111.992920  0.000161  0.156007   4.829283  4.749948
           ZBRA     223.960007  0.000133  0.492315   5.677342  5.400991
           ZION      33.581326  0.000292  0.375453   3.638202  3.527329
           ZTS      176.048248  0.000072  0.938253   5.276568  5.158939

Price               band_med        rsi
Date       Tickers
2010-01-31 A             NaN        NaN
           AAL           NaN        NaN
           AAPL          NaN        NaN
           ABT           NaN        NaN
           ACGL          NaN        NaN
...                      ...        ...
2023-09-30 YUM      4.851489  36.057193
           ZBH      4.789615  31.893251
           ZBRA     5.539167  29.494977
           ZION     3.582765  46.707775
           ZTS      5.217753  42.623481

[78880 rows x 7 columns]

In [142]:
df_m=pd.concat([df.unstack('Tickers')['dollar_volume'].resample('M').mean().stack('Tickers'),
           df.unstack('Tickers')[last_col].resample('M').last().stack('Tickers')], axis=1).dropna()

In [143]:
df_m.rename(columns={0:'dollar_volume'}, inplace=True)

In [144]:
df_m.columns

Index(['dollar_volume', 'Adj Close', 'Garman', 'atr', 'band_high', 'band_low',
       'band_med', 'rsi'],
      dtype='object')

In [145]:
df_m['dollar_volume'] = df_m['dollar_volume'].unstack('Tickers').rolling(5*12, min_periods=1).mean().stack()
df_m

                    dollar_volume   Adj Close    Garman       atr  band_high  \
Date       Tickers
2010-02-28 A           110.000684   20.257940 -0.003401 -0.926605   3.072558
           AAL          74.056717    6.910295  0.000929 -1.406414   2.119660
           AAPL       3406.410483    6.194724 -0.009069 -0.821805   1.979530
           ABT         303.907339   19.121838 -0.036352 -0.926390   3.016738
           ACGL         47.208270    8.220000  0.000043 -1.005321   2.229311
...                           ...         ...       ...       ...        ...
2023-09-30 OTIS        171.884422   78.967529  0.000040 -1.028320   4.468390
           ABNB        909.311388  132.279999  0.000213 -1.006939   5.024801
           CEG         175.734549  108.239204  0.000220 -0.436215   4.735953
           GEHC        226.596749   66.153511  0.000185 -0.893478   4.270855
           KVUE        664.096862   20.426666  0.000136 -0.899746   3.184098

                    band_low  band_med        rsi
Date       Tickers
2010-02-28 A        2.951036  3.011797  60.696958
           AAL      1.784828  1.952244  72.203237
           AAPL     1.914367  1.946949  51.538127
           ABT      2.977618  2.997178  50.335824
           ACGL     2.158331  2.193821  62.969750
...                      ...       ...        ...
2023-09-30 OTIS     4.377807  4.423099  33.116240
           ABNB     4.857047  4.940924  44.494127
           CEG      4.655604  4.695779  55.245466
           GEHC     4.155782  4.213319  40.922326
           KVUE     3.034066  3.109082  35.706317

[78383 rows x 8 columns]

In [146]:
df_m['dollar_vol_rank']=df_m.groupby(by='Date')['dollar_volume'].rank(ascending=False)
top150=df_m[df_m['dollar_vol_rank']<150]
top150.drop(columns=['dollar_vol_rank', 'dollar_volume'], inplace=True)
top150

                     Adj Close    Garman       atr  band_high  band_low  \
Date       Tickers
2010-02-28 AAPL       6.194724 -0.009069 -0.821805   1.979530  1.914367
           ABT       19.121838 -0.036352 -0.926390   3.016738  2.977618
           ACN       30.723017 -0.025545 -0.887751   3.497278  3.448172
           ADBE      34.650002  0.000170 -0.785395   3.577503  3.471929
           ADM       20.634808 -0.049244 -0.783039   3.124081  3.061069
...                        ...       ...       ...        ...       ...
2023-09-30 PYPL      58.930000  0.000099 -0.689842   4.201794  4.079868
           MRNA      98.120003  0.000146 -0.529511   4.788149  4.582514
           UBER      44.270000  0.000441 -0.746098   3.917801  3.806654
           ABNB     132.279999  0.000213 -1.006939   5.024801  4.857047
           KVUE      20.426666  0.000136 -0.899746   3.184098  3.034066

                    band_med        rsi
Date       Tickers
2010-02-28 AAPL     1.946949  51.538127
           ABT      2.997178  50.335824
           ACN      3.472725  38.000217
           ADBE     3.524716  52.900927
           ADM      3.092575  39.949605
...                      ...        ...
2023-09-30 PYPL     4.140831  40.148614
           MRNA     4.685332  38.747314
           UBER     3.862227  45.005268
           ABNB     4.940924  44.494127
           KVUE     3.109082  35.706317

[24436 rows x 7 columns]

4. calculatiing  montly returns for diffrent time horizons

In [147]:
def cal_return(df): 
    outliers_cutoff = 0.005
    lag_periods = [1, 2, 3, 6, 9, 12]
    for lag in lag_periods:
        df[f'return_{lag}m'] = (df['Adj Close'].pct_change(lag)
                                .pipe(lambda x: x.clip(lower=x.quantile(outliers_cutoff),
                                                      upper=x.quantile(1 - outliers_cutoff)))
                                .add(1).pow(1/lag).sub(1))
    return df

In [148]:
top150=top150.groupby(level=1,group_keys=False).apply(cal_return).dropna()

In [149]:
top150

                     Adj Close    Garman       atr  band_high  band_low  \
Date       Tickers
2011-02-28 AAPL      10.693180 -0.009785 -0.785660   2.489931  2.414105
           ABT       17.550585 -0.027785 -0.985407   2.914980  2.851020
           ACN       40.314213 -0.025488 -0.845081   3.765468  3.714392
           ADBE      34.500000  0.000285 -0.794966   3.586708  3.514554
           AFL       21.454905 -0.035942 -0.503081   3.117474  3.064250
...                        ...       ...       ...        ...       ...
2023-09-30 ETSY      61.869999  0.000604 -0.333957   4.348714  4.106247
           PYPL      58.930000  0.000099 -0.689842   4.201794  4.079868
           MRNA      98.120003  0.000146 -0.529511   4.788149  4.582514
           UBER      44.270000  0.000441 -0.746098   3.917801  3.806654
           ABNB     132.279999  0.000213 -1.006939   5.024801  4.857047

                    band_med        rsi  return_1m  return_2m  return_3m  \
Date       Tickers
2011-02-28 AAPL     2.452018  56.779898   0.040935   0.046433   0.043168
           ABT      2.883000  59.780148   0.065102   0.006621   0.014387
           ACN      3.739930  51.769543   0.000194   0.030370   0.059213
           ADBE     3.550631  58.212509   0.043873   0.058706   0.074628
           AFL      3.090862  56.978510   0.027669   0.024018   0.047384
...                      ...        ...        ...        ...        ...
2023-09-30 ETSY     4.227481  31.886518  -0.159032  -0.219835  -0.099080
           PYPL     4.140831  40.148614  -0.057271  -0.118390  -0.040588
           MRNA     4.685332  38.747314  -0.132219  -0.086803  -0.068763
           UBER     3.862227  45.005268  -0.062672  -0.053920   0.008422
           ABNB     4.940924  44.494127   0.005549  -0.067704   0.010603

                    return_6m  return_9m  return_12m
Date       Tickers
2011-02-28 AAPL      0.064244   0.036017    0.046543
           ABT      -0.001325   0.004235   -0.007120
           ACN       0.059652   0.036910    0.022899
           ADBE      0.037265   0.008113   -0.000361
           AFL       0.039168   0.033995    0.016553
...                       ...        ...         ...
2023-09-30 ETSY     -0.092384  -0.070370   -0.038969
           PYPL     -0.041385  -0.020827   -0.031074
           MRNA     -0.071952  -0.064976   -0.015431
           UBER      0.057244   0.066838    0.043691
           ABNB      0.010289   0.048608    0.019401

[21760 rows x 13 columns]

In [150]:
ticker = 'F-F_Research_Data_5_Factors_2x3'

# Fetch the data using yfinance
ff_factors = yf.download(ticker, start='2010')

[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['F-F_RESEARCH_DATA_5_FACTORS_2X3']: Exception('%ticker%: No timezone found, symbol may be delisted')

In [151]:

dataset_name = 'F-F_Research_Data_5_Factors_2x3'
start_date = '2010-01-01'

# Fetch the data using pandas_datareader
ff_factors = web.DataReader(dataset_name, 'famafrench', start=start_date)[0]

ff_factors.drop(columns=['RF'], inplace=True)
print(ff_factors)

         Mkt-RF   SMB   HML   RMW   CMA
Date
2010-01   -3.36  0.34  0.43 -1.27  0.46
2010-02    3.40  1.51  3.23 -0.27  1.43
2010-03    6.31  1.85  2.21 -0.65  1.69
2010-04    2.00  4.98  2.89  0.69  1.72
2010-05   -7.89  0.04 -2.44  1.30 -0.21
...         ...   ...   ...   ...   ...
2023-07    3.21  2.86  4.11 -0.57  0.57
2023-08   -2.39 -3.65 -1.06  3.43 -2.37
2023-09   -5.24 -1.80  1.52  1.86 -0.83
2023-10   -3.19 -4.04  0.19  2.46 -0.66
2023-11    8.84 -0.10  1.65 -3.89 -0.99

[167 rows x 5 columns]

In [152]:
ff_factors.index=ff_factors.index.to_timestamp()

In [153]:
factor_data=ff_factors.resample('M').last()/100

In [154]:
factor_data=factor_data.join(top150['return_1m'])
factor_data

                    Mkt-RF     SMB     HML     RMW     CMA  return_1m
Date       Tickers
2011-02-28 AAPL     0.0349  0.0165  0.0127 -0.0194  0.0088   0.040935
           ABT      0.0349  0.0165  0.0127 -0.0194  0.0088   0.065102
           ACN      0.0349  0.0165  0.0127 -0.0194  0.0088   0.000194
           ADBE     0.0349  0.0165  0.0127 -0.0194  0.0088   0.043873
           AFL      0.0349  0.0165  0.0127 -0.0194  0.0088   0.027669
...                    ...     ...     ...     ...     ...        ...
2023-09-30 ETSY    -0.0524 -0.0180  0.0152  0.0186 -0.0083  -0.159032
           PYPL    -0.0524 -0.0180  0.0152  0.0186 -0.0083  -0.057271
           MRNA    -0.0524 -0.0180  0.0152  0.0186 -0.0083  -0.132219
           UBER    -0.0524 -0.0180  0.0152  0.0186 -0.0083  -0.062672
           ABNB    -0.0524 -0.0180  0.0152  0.0186 -0.0083   0.005549

[21760 rows x 6 columns]

In [155]:
all_stocks=factor_data.groupby(level=1, group_keys=False).size()
stck_10=all_stocks[all_stocks>=10]
stck_10

Tickers
A        23
AAL      99
AAPL    152
ABBV    117
ABNB     21
       ...
WMB      16
WMT     152
WYNN    149
XOM     152
YUM      97
Length: 207, dtype: int64

In [156]:
factor_data=factor_data[factor_data.index.get_level_values('Tickers').isin(stck_10.index)]
factor_data

                    Mkt-RF     SMB     HML     RMW     CMA  return_1m
Date       Tickers
2011-02-28 AAPL     0.0349  0.0165  0.0127 -0.0194  0.0088   0.040935
           ABT      0.0349  0.0165  0.0127 -0.0194  0.0088   0.065102
           ACN      0.0349  0.0165  0.0127 -0.0194  0.0088   0.000194
           ADBE     0.0349  0.0165  0.0127 -0.0194  0.0088   0.043873
           AFL      0.0349  0.0165  0.0127 -0.0194  0.0088   0.027669
...                    ...     ...     ...     ...     ...        ...
2023-09-30 NCLH    -0.0524 -0.0180  0.0152  0.0186 -0.0083  -0.071213
           PYPL    -0.0524 -0.0180  0.0152  0.0186 -0.0083  -0.057271
           MRNA    -0.0524 -0.0180  0.0152  0.0186 -0.0083  -0.132219
           UBER    -0.0524 -0.0180  0.0152  0.0186 -0.0083  -0.062672
           ABNB    -0.0524 -0.0180  0.0152  0.0186 -0.0083   0.005549

[21710 rows x 6 columns]

In [157]:
betas=factor_data.groupby(level=1, group_keys=False).apply(lambda group: RollingOLS(endog=group['return_1m'],
                  exog=sm.tools.tools.add_constant(group.drop('return_1m', axis=1)),
                  min_nobs=len(group.columns) + 1).fit(params_only=True).params)
betas.drop(columns=['const'], inplace=True)
betas.head()

                    Mkt-RF  SMB  HML  RMW  CMA
Date       Tickers
2011-02-28 AAPL        NaN  NaN  NaN  NaN  NaN
           ABT         NaN  NaN  NaN  NaN  NaN
           ACN         NaN  NaN  NaN  NaN  NaN
           ADBE        NaN  NaN  NaN  NaN  NaN
           AFL         NaN  NaN  NaN  NaN  NaN

In [158]:
betas.columns

Index(['Mkt-RF', 'SMB', 'HML', 'RMW', 'CMA'], dtype='object')

In [160]:
factors = ['Mkt-RF', 'SMB', 'HML', 'RMW', 'CMA']

top150= (top150.join(betas.groupby(level=1).shift()))

ValueError: columns overlap but no suffix specified: Index(['Mkt-RF', 'SMB', 'HML', 'RMW', 'CMA'], dtype='object')

In [162]:
top150.loc[:,factors]=top150.groupby(level=1)[factors].apply(lambda  x: x.fillna(x.mean()))

ValueError: operands could not be broadcast together with shapes (21760,2) (3,) (21760,2)